language: python

env:
  DATABASE_URL="dbname='safaricom' host='127.0.0.1' port='5432' user='postgres' password=''"
  DATABASE_TEST_URL="dbname='safaricom' host='127.0.0.1' port='5432' user='postgres' password=''"
  APP_SETTINGS="testing"

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov nose

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - psql -c 'CREATE DATABASE safaricom' -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres ;" -U postgres


script:
  - nosetests --with-coverage --cover-package=app app -v

after_success:
  - coveralls
  - codecov --token=